spring.application.name=cafeteria
spring.datasource.url=jdbc:postgresql://localhost:5432/cafeteria
spring.datasource.username=postgres
spring.datasource.password=balu2011
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect